---
title: "Self Evaluation L01 Review"
subtitle: |
  | Data Science 2 with R 
  | STAT 301-2
author: "Isaac Rhee"
pagetitle: "Self Evaluation PQ2 Isaac Rhee"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false
  error: true

from: markdown+emoji
reference-location: margin
citation-location: margin 
---

::: {.callout-tip icon="false"}
## Github Repo Link

[https://github.com/stat301-3-2026-spring/l01-review-isaacrhee25](https://github.com/stat301-3-2026-spring/l01-review-isaacrhee25)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

- Collect/clean data
- Split the data
- Create recipes
- Select and train models
- Tune hyperparameters if necessary
- Evaluate model performance
- Select best model
- Evaluate final model on test set

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

I forgot to add setting up a resampling technique and assessing the best model on the testing data.



:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning uses data where each observation has a known outcome. The goal is to learn a relationship between predictors and the target variable to make predictions on new data. Unsupervised learning uses data where no outcome variable is provided. The goal is to identify patterns in the data.  

:::

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

I think I defined both well. 




:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

The goal of descriptive models is to summarize and explore the structure of the data. These models help identify patterns, trends, and relationships without making formal predictions or drawing causal conclusions. They are often used for data exploration and visualization

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

Inferential models aim to draw conclusions about a population based on a sample of data. The focus is on understanding relationships between variables and determining whether those relationships are statistically significant. These models are commonly used for hypothesis testing and estimating effects

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

Predictive models are designed to make accurate predictions on new, unseen data.

:::

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

I think my answers are good




:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model assumes f(x) follows some known form or equation, and estimates a set of parameters. 

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

An empirically driven model makes no assumptions about the form of f(x)

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are typically parametric, and empirically drive models are often nonparametric. 

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

Mechanistic models because they are based on known relationships and the parameters often have clear meanings. 

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Empirically driven models are more flexible than mechanistic models. 

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models have higher bias and lower variance, while empirically driven models have lower bias and higher variance. 

:::

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

I think my answers were good.




:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Regression is used for continuous outcome variables. The goal is to predict a value. Classification is used for cateogrical outcome variables. The goal is to assign observations to a class or category. 

:::

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

I think my answer was good. 




:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying by the outcome/target variable ensures that both the training and testing sets have approximately the same proportion of each class as the original dataset. Basically, it keeps the class distribution consistent across splits. 
:::

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

I think my answer was good




:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation first splits the training data into v folds, and the model is trained on v-1 folds and evaluated on the remaining fold. This process is repeated v times, so each fold is the remaining fold once. With repeats, the entire process is performed multiple times with different splits. The RMSE is calculated on each validation fold and averaged across all folds and repeats to estimate the model’s test performance. We use it to provide a more robust estimate of test error than the training/test split. 

:::

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

I don't think I was detailed enough on the advantage of using v-fold cross validation.





:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

We might use a boostrap resampling procedure when the dataset is small. 

:::

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
3

## Explanation

I didn't have anything about low variance

## Updated solution

If we want our estimate of the test RMSE to have very low variance then we should use a bootstrap resampling procedure instead of v-fold cross validation (we can run many more bootstraps than folds). Also we might use a boostrap resampling procedure when the dataset is small. 


:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tuning is the process of selecting the best hyperparameters to improve model performance. We use it because proper tuning can improve model performance and ensure the model generalizes well to new data. 
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

I didn't say that hyperparameters are user specified and I could have been a little more detailed. 



:::


### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

RMSE and MAE. 

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

ROC AUC and Accuracy. 
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation
My answers were correct



:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Inferential. The goal is to understand relationship/effect of number of service calls on churn.

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Prediction. The goal is to estimate or predict an outcome (churn) for customers based on observed predictors. 

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

My answers were correct

:::
